version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
      MYSQL_USER: ${MYSQLDB_USER}
      MYSQL_PASSWORD: ${MYSQLDB_PASSWORD}
    ports:
      - "${MYSQLDB_LOCAL_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uapp_user", "-pShepard27!" ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - app_network
  spring_app:
    build: .
    container_name: spring_app
    restart: on-failure
    env_file: ./.env
    depends_on:
      mysqldb:
        condition: service_healthy

    environment:
      MYSQLDB_HOST: mysqldb
      SERVER_PORT: ${SPRING_LOCAL_PORT}

    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_LOCAL_PORT}"

    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data: